language: crystal

before_install:
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - sudo apt-get -qq update
  - sudo apt-get install -y default-jdk haskell-platform mono-mcs

install: make clean build

script: make test
